package com.interviewscheduler.scheduling;

public enum ConflictType {
    CANDIDATE_CONFLICT,
    INTERVIEWER_CONFLICT,
    RECRUITER_CONFLICT,
    HIRING_MANAGER_CONFLICT,
    CALENDAR_CONFLICT,
    WORKING_HOURS_CONFLICT,
    BUFFER_CONFLICT,
    NOTICE_PERIOD_CONFLICT,
    INVALID_TIME_RANGE,
    ROUND_DEPENDENCY_CONFLICT
}
